### ISSUE TITLE
Articles: html

### ISSUE THREAD

**Issue by lucymonie** [GlobeTownDevs/blog#12]
Content required from @marisid @tbtommyb @njsfield @lucymonie
- Profile pic
- Profile text content
- Social media links (github, twitter, linkedin, codewars)
- Project links

**Comment by njsfield** [comment]
![me-github](https://cloud.githubusercontent.com/assets/16468314/19538965/9fba9750-964e-11e6-9f29-954b0a25b315.png)

**Text content**
I started my coding journey in December 2015, whilst I was trying to design a site to host a music portfolio. I was using a website builder to try and put everything together, and wanted to learn how to make something from scratch. Since then I’ve been learning front/back end technologies, attending meetups in London, creating small websites for family and friends and spending lots of hours on codewars. I love to learn new things, solve problems and work with others on projects. I’m also excited for the future of the web!

**Social Links**
https://github.com/njsfield 
https://twitter.com/nickjsfield
https://uk.linkedin.com/in/nickjackstanleyfield
https://www.codewars.com/users/njsfield

**Project Links**
Lunar Lander - http://njsfield.github.io/Lunar-Lander/ 
Nearest Asteroids - https://njsfield.github.io/Nearest-Asteroid-Visual/
Musical Text - https://njsfield.github.io/Musical-Text/
Calculator - https://njsfield.github.io/calculator/
Weather App - https://njsfield.github.io/Weather-App/

**Comment by lucymonie** [comment]
**Bio**
I got into coding after reading an article by Adda Birnir, the founder of [skillcrush.com](skillcrush.com), a online code school. The article talked about the great potential for people with tech skills to find meaningful, creative and flexible work, and the need for increased diversity in the industry. My background is in publishing and editing, and I have found coding requires similar creativity, judgement and precision. I feel extremely fortunate and excited to be studying web development at Founders & Coders.

**Social**
github https://github.com/lucymonie
twitter https://twitter.com/lucymonie
linkedin www.linkedin.com/in/lucy-monie
codewars https://www.codewars.com/users/lucymonieProject Links

Projects
Stopwatch http://lucymoniehall.com/stopwatch/
Pomodoro http://lucymoniehall.com/tomato-timer/
Calculator http://lucymoniehall.com/calculator/

**Comment by marisid** [comment]
### Bio

I'm Marina and six months ago I decided to make a career change into the exciting world of web development. I have a civil engineering background but I started learning to code to combine my technical skills with creativity. Since then, I have developed my coding skills by attending several workshops and tech events and by studying various online resources. I currently take part in an intensive coding course with Founders and Coders to become a full stack JavaScript developer. I love building nice functional apps and websites and learning new technologies. So, get in touch for feedback, questions or even just to say hi!

### Social media links
- https://uk.linkedin.com/in/marina-sideri-480915b7
- https://twitter.com/sid_marinako
- https://github.com/marisid
- https://www.codewars.com/users/marisid

### Portfolio links
- http://codepen.io/marisid/full/zBZoJg/ --> Weather app
- http://codepen.io/marisid/pen/zBpvZE --> quote generator
- http://codepen.io/marisid/pen/BzVjRq --> Tribute page to M.C. Escher

**Comment by tbtommyb** [comment]
I started coding after realising that being a developer was far preferable to my previous career in the civil service. I'm trying to learn all I can about computers and programming, with a particular interest in web development and audio programming. I'm currently on the Founders & Coders bootcamp to become a full-stack developer.

Social media
- https://uk.linkedin.com/in/thomas-barrett-bb071041
- https://github.com/tbtommyb
- https://twitter.com/tbtommyb
- https://www.codewars.com/users/tbtommyb

Portfolio links
- https://www.concertspot.co.uk/
